// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igpqkdkgpkbrmcshhydp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncHFrZGtncGticm1jc2hoeWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODA3NzksImV4cCI6MjA1NTM1Njc3OX0.PS-FxmabKSS-TlLMdEZzFMnIIoDKus6ZBPBLBXXwx90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);